name: "Initialize terraform"
description: "Initialize the terraform based on the inputs from the GS repos"

inputs:
  MY_SECRET:
    description: "My secret"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: run bash script
      run:  init.sh 
      shell: bash
      env:
        MY_SECRET: ${{ inputs.MY_SECRET }}
