name: build-test-deploy-sample
on:
    workflow_call:
        inputs:
            your-name:
                description: "Your Name"
                required: true
                type: string
            DOCKER_USERNAME:
                description: "Your Name"
                required: true
                type: string
            REPOSITORY_NAME:
                description: "Your Name"
                required: true
                type: string
            TAG_NAME:
                description: "Tag name"
                required: false
                type: string
        secrets:
            MY_SECRET: 
                required: true
            DOCKER_TOKEN:
                required: true

jobs:
    terrraform:
        strategy:
            matrix:
                cmds: [plan, apply]
                exclude: 
                    - cmds: ${{github.ref_name != 'main' && github.ref_name != 'master' && 'apply' }}
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - run : echo "Running workflow for ${{matrix.cmds}} on branch ${{github.ref_name}}"
            - run: echo "Run ${{matrix.cmds}} ${{ inputs.your-name }}"
            - run: env
    
    build:
        runs-on: ubuntu-latest
        env:
            MY_SECRET: ${{ secrets.MY_SECRET}}

        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            
            - run: echo "Hello ${{ inputs.your-name }}"
            - name: run bash script
              run: ./init.sh 
              

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            
            - run: echo "Testing you name ${{ inputs.your-name }}"
            - run: env
            

    build-push:
        runs-on: ubuntu-latest
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ inputs.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
                platforms: linux/amd64,linux/arm64
                push: true
                tags: ${{ inputs.DOCKER_USERNAME }}/${{ inputs.REPOSITORY_NAME }}:${{inputs.TAG_NAME}}