name: build-test-deploy-sample
on:
    workflow_call:
        inputs:
            branch_name:
                description: "Your main branch name"
                required: true
                type: string
            DOCKER_USERNAME:
                description: "Your Name"
                required: true
                type: string
            REPOSITORY_NAME:
                description: "Your Name"
                required: true
                type: string
            TAG_NAME:
                description: "Tag name"
                required: false
                type: string
            branch_type:
                description: "checking the prod branch"
                required: false
                type: boolean
                default: ${{ github.ref_name == 'main' || github.ref_name == 'master'}}
        secrets:
            MY_SECRET: 
                required: true
            DOCKER_TOKEN:
                required: true

jobs:
        
    terrraform:
        strategy:
            max-parallel: 1
            matrix:
                cmds: [plan, apply]
                exclude: 
                    # - cmds:  ${{ contains(github.ref_name, 'master') || contains(github.ref_name, 'main') && 'plan' || 'apply'}}
                    # - cmds: ${{ github.ref_name != 'master' || github.ref_name != 'main' && 'apply'|| 'plan'}}
                    - cmds: ${{ inputs.branch_type == 'true' && 'apply' || 'plan' }}
                    # - cmds: ${{github.ref_name == inputs.branch_name && 'plan' }}
                

        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            - run : echo "Running workflow for ${{matrix.cmds}} on branch ${{github.ref_name}}"
            - run : echo "branch type is ${{inputs.branch_type}}"
            - run: echo "Run ${{matrix.cmds}} ${{ inputs.branch_name }}"
            - run: env
    
    # build:
    #     runs-on: ubuntu-latest
    #     env:
    #         MY_SECRET: ${{ secrets.MY_SECRET}}

    #     steps:
    #         - name: checkout repo
    #           uses: actions/checkout@v3
            
    #         - run: echo "Hello ${{ inputs.branch_name }}"
    #         - name: run bash script
    #           run: ./init.sh 
              

    # test:
    #     needs: build
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: checkout repo
    #           uses: actions/checkout@v3
            
    #         - run: echo "Testing you name ${{ inputs.branch_name }}"
    #         - run: env
            

    # build-push:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Login to Docker Hub
    #         uses: docker/login-action@v3
    #         with:
    #             username: ${{ inputs.DOCKER_USERNAME }}
    #             password: ${{ secrets.DOCKER_TOKEN }}
    #       - name: Set up Docker Buildx
    #         uses: docker/setup-buildx-action@v3
    #       - name: Build and push
    #         uses: docker/build-push-action@v6
    #         with:
    #             platforms: linux/amd64,linux/arm64
    #             push: true
    #             tags: ${{ inputs.DOCKER_USERNAME }}/${{ inputs.REPOSITORY_NAME }}:${{inputs.TAG_NAME}}