name: build-test-deploy-sample
on:
    workflow_call:
        inputs:
            your-name:
                description: "Your Name"
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            
            - run: echo "Hello ${{ inputs.your-name }}"
              

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            
            - run: echo "Testing you name ${{ inputs.your-name }}"
            

