name: build-test-deploy-sample
on:
    workflow_call:
        inputs:
            your-name:
                description: "Your Name"
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            super_secret: ${{ secrets.MY_SECRET}}
            my_secret: ${{ secrets.MY_SECRET}}
        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            
            - run: echo "Hello ${{ inputs.your-name }}"
            - name: run bash script
              run: ./init.sh 
              

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v3
            
            - run: echo "Testing you name ${{ inputs.your-name }}"
            

